const $=s=>document.querySelector(s);const LS={users:'rr_users',active:'rr_active',prefs:'rr_prefs',progress:'rr_progress',remember:'rr_remember_email'};
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function activeUser(){const email=localStorage.getItem(LS.active);return get(LS.users,[]).find(u=>u.email===email)||null}
function requireLogin(){if(!activeUser()) location.href='login.html'}
function nav(){const n=$('.links'); if(!n)return; const u=activeUser(); n.innerHTML=u?`<a href="dashboard.html">Dashboard</a><a href="garage.html">Garage</a><a href="profile.html">Profile</a><button class="btn danger" onclick="logout()">Logout</button>`:`<a href="login.html">Login</a><a href="register.html">Register</a>`}
function logout(){localStorage.removeItem(LS.active); location.href='index.html'}
function toast(msg){let t=$('.toast')||document.body.appendChild(Object.assign(document.createElement('div'),{className:'toast'}));t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function initAuth(){nav(); const reg=$('#registerForm'), log=$('#loginForm'); if(log){const saved=localStorage.getItem(LS.remember); if(saved){$('#email').value=saved; const cb=$('#rememberMe'); if(cb)cb.checked=true;} const forgot=$('#forgotBtn'), fmodal=$('#forgotModal'); if(forgot&&fmodal){forgot.onclick=()=>fmodal.classList.add('active'); $('#closeForgot').onclick=()=>fmodal.classList.remove('active'); $('#resetBtn').onclick=resetPassword;}}
 if(reg) reg.onsubmit=e=>{e.preventDefault();let users=get(LS.users,[]);let name=$('#name').value.trim(),email=$('#email').value.trim().toLowerCase(),pass=$('#password').value;if(users.some(u=>u.email===email))return toast('Account already exists. Please login.');users.push({name,email,pass,joined:new Date().toLocaleDateString(),bestScore:0,coins:0,totalQuestions:0,correctQuestions:0});set(LS.users,users);localStorage.setItem(LS.active,email);set(LS.prefs,{car:'classic',gender:'female',setupDone:false});set(LS.progress,{unlocked:1,level:1});location.href='driver.html'};
 if(log) log.onsubmit=e=>{e.preventDefault();let u=get(LS.users,[]).find(x=>x.email===$('#email').value.trim().toLowerCase()&&x.pass===$('#password').value);if(!u)return toast('Wrong email or password.');localStorage.setItem(LS.active,u.email); if($('#rememberMe')&&$('#rememberMe').checked)localStorage.setItem(LS.remember,u.email); else localStorage.removeItem(LS.remember); let prefs=get(LS.prefs,{setupDone:false});location.href=prefs.setupDone?'dashboard.html':'driver.html'};
}

function resetPassword(){
 const email=($('#resetEmail')?.value||'').trim().toLowerCase(), pass=$('#newPassword')?.value||'';
 if(!email||pass.length<4) return toast('Enter email and at least 4 characters for password.');
 let found=false; const users=get(LS.users,[]).map(u=>{if(u.email===email){found=true;return {...u,pass}} return u});
 if(!found) return toast('No registered account found with this email.');
 set(LS.users,users); $('#forgotModal')?.classList.remove('active'); toast('Password updated. You can login now.');
}

function renderDashboard(){requireLogin();nav();let u=activeUser(),p=get(LS.progress,{unlocked:1}),prefs=get(LS.prefs,{car:'classic',gender:'female',setupDone:false}); if(!prefs.setupDone){location.href='driver.html';return} $('#hello').textContent=`Welcome, ${u.name}`;$('#dashStats').innerHTML=`<div class="stat"><b>Coins</b><span>💰 ${u.coins||0}</span></div><div class="stat"><b>Best Score</b><span>⭐ ${u.bestScore||0}</span></div><div class="stat"><b>Unlocked Level</b><span>Level ${p.unlocked}</span></div><div class="stat"><b>Driver</b><span>${prefs.gender==='male'?'👦 Male':'👧 Female'}</span></div><div class="stat"><b>Accuracy</b><span>${u.totalQuestions?Math.round((u.correctQuestions||0)/u.totalQuestions*100):0}%</span></div>`;renderLevels()}
function renderLevels(){let p=get(LS.progress,{unlocked:1});let box=$('#levelCards'); if(!box)return; const data=[['1','Safe Password City','Reach 1,500m and clear 5 password/privacy checkpoints.'],['2','Phishing Highway','Faster traffic, scam popups and 5 phishing checkpoints.'],['3','Dark Web Rush','High-speed cyber storm with 5 advanced security checkpoints.']];box.innerHTML=data.map(([n,t,d])=>`<div class="card level-card ${p.unlocked<+n?'locked':''}"><span class="badge">Level ${n}</span><h2>${t}</h2><p class="muted">${d}</p><button class="btn primary" ${p.unlocked<+n?'disabled':''} onclick="startLevel(${n})">${p.unlocked<+n?'🔒 Locked':'▶ Start Mission'}</button></div>`).join('')}
function startLevel(n){set(LS.progress,{...get(LS.progress,{unlocked:1}),level:n});location.href='game.html'}
function renderGarage(){requireLogin();nav();let prefs=get(LS.prefs,{car:'classic',gender:'female',setupDone:true});let cars=[['classic','Classic White','#ffffff','#aef8ff','Balanced control'],['neon','Neon Cyber','#38e8ff','#ff4fd8','Sharper turning'],['shadow','Shadow GT','#29314e','#8a7cff','Better stability'],['gold','Gold Racer','#ffd84a','#ff8b3d','Premium look']];$('#cars').innerHTML=cars.map(c=>`<div class="card garage-car ${prefs.car===c[0]?'selected':''}" onclick="chooseCar('${c[0]}')"><div class="car3d" style="--car1:${c[2]};--car2:${c[3]}"><i class="wheel w1"></i><i class="wheel w2"></i><i class="wheel w3"></i><i class="wheel w4"></i><b class="body"></b><b class="top"></b><i class="light l"></i><i class="light r"></i></div><h3>${c[1]}</h3><p class="muted">${c[4]}</p></div>`).join('');$('#avatars').innerHTML=`<button class="mini-choice ${prefs.gender==='female'?'selected':''}" onclick="chooseGender('female')">👧 Female</button><button class="mini-choice ${prefs.gender==='male'?'selected':''}" onclick="chooseGender('male')">👦 Male</button>`}
function chooseCar(car){let prefs=get(LS.prefs,{});prefs.car=car;set(LS.prefs,prefs);renderGarage();toast('Car selected')}
function chooseGender(g){let prefs=get(LS.prefs,{});prefs.gender=g;set(LS.prefs,prefs); if($('#avatars')) renderGarage(); if($('#driverPick')) renderDriver(); toast('Driver selected')}
function finishSetup(){let prefs=get(LS.prefs,{gender:'female',car:'classic'});prefs.setupDone=true;set(LS.prefs,prefs);location.href='dashboard.html'}
function renderDriver(){requireLogin();nav();let prefs=get(LS.prefs,{car:'classic',gender:'female'});$('#driverPick').innerHTML=`<div class="setup-panel"><h2>Choose your driver</h2><p class="muted">This appears only during first setup. You can change it later from Garage.</p><div class="compact-options"><button class="driver-chip ${prefs.gender==='female'?'selected':''}" onclick="chooseGender('female')"><span>👧</span><b>Female</b></button><button class="driver-chip ${prefs.gender==='male'?'selected':''}" onclick="chooseGender('male')"><span>👦</span><b>Male</b></button></div><button class="btn primary" onclick="finishSetup()">Continue to Dashboard</button></div>`}
function renderProfile(){requireLogin();nav();let u=activeUser(),prefs=get(LS.prefs,{}),p=get(LS.progress,{unlocked:1});$('#profileBox').innerHTML=`<h2>${u.name}</h2><p class="muted">${u.email}</p><div class="stat"><b>Driver</b><span>${prefs.gender==='male'?'👦 Male':'👧 Female'}</span></div><div class="stat"><b>Selected Car</b><span>${prefs.car||'classic'}</span></div><div class="stat"><b>Coins</b><span>💰 ${u.coins||0}</span></div><div class="stat"><b>Best Score</b><span>⭐ ${u.bestScore||0}</span></div><div class="stat"><b>Unlocked</b><span>Level ${p.unlocked}</span></div><div class="stat"><b>Cyber Quiz Accuracy</b><span>${u.totalQuestions?Math.round((u.correctQuestions||0)/u.totalQuestions*100):0}%</span></div>`}
document.addEventListener('DOMContentLoaded',initAuth);